name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2

      - name: Cache â˜•
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-npm-caches-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install ðŸ”§
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build ðŸ”§
        run: |
          yarn run build
          cd docs
          cp index.html 404.html
          echo "${{ secrets.CNAME }}" > CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGE_ACTION_TOKEN }}
          publish_dir: ./dist
